sudo: false
language: python
env:
  - TOXENV=py34
services:
  - postgresql
before_install: psql -c 'CREATE DATABASE simplewiki' -U postgres
install: pip install tox
script: tox
cache:
  directories:
    - .tox
